language: go
services:
  - docker
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
os:
  - linux
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on make test

before_script:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#postgresql
  - sudo /etc/init.d/postgresql stop