version: '3'
services:
  redis:
    image: redis:latest
    #command: ["redis-server"]
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    #command: ["redis-server"]
    ports:
      - "5432:5432"